apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nlp-ai-service-hpa
  namespace: nlp-ai
  labels:
    app: nlp-ai-service
    version: v1.0.0
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nlp-ai-service
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Pods
      pods:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: "100"
    - type: Pods
      pods:
        metric:
          name: redis_cache_hit_ratio
        target:
          type: AverageValue
          averageValue: "0.8"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
        - type: Pods
          value: 4
          periodSeconds: 60
      selectPolicy: Max
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: nlp-ai-service-monitor
  namespace: nlp-ai
  labels:
    app: nlp-ai-service
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: nlp-ai-service
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nlp-ai-service-pdb
  namespace: nlp-ai
  labels:
    app: nlp-ai-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: nlp-ai-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nlp-ai-config
  namespace: nlp-ai
  labels:
    app: nlp-ai-service
data:
  # HPA Configuration
  hpa-cpu-target: "70"
  hpa-memory-target: "80"
  hpa-min-replicas: "2"
  hpa-max-replicas: "20"
  
  # Cache Configuration
  redis-cache-ttl: "600"
  redis-cache-enabled: "true"
  
  # Rate Limiting
  rate-limit-requests: "100"
  rate-limit-window: "60"
  
  # Monitoring
  metrics-enabled: "true"
  health-check-interval: "30"



